spa/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from inv import (views, ventas, compras, pagos, caja, productos, servicios, paquetes, sesiones, ordenes, clientes,
                 panelclientes, panelcolaborador, proveedores, cajeros, consultas, estadisticas)

from spa.settings import STATIC_URL, STATIC_ROOT, MEDIA_URL, MEDIA_ROOT

urlpatterns = [

    # Admin
    url(r'^admin/', include(admin.site.urls)),

    # Home
    url(r'^$', views.index, name='index'),

    # Login
    url(r'^login$', views.login_user, name='login_user'),

    # Logout
    url(r'^logout$', views.logout_user, name='logout_user'),

    # Change passw
    url(r'^pass$', views.passwd, name='change_password'),

    # Get Data API
    url(r'^get_data$', views.get_data, name='get_data'),

    # Subir Video
    url(r'^subir_video$', views.subir_video, name='subir_video'),

    # VENTAS
    url(r'^ventas$', ventas.view, name='ventas'),

    # COMPRAS
    url(r'^compras$', compras.view, name='compras'),

    # PAGOS
    url(r'^pagos$', pagos.view, name='pagos'),

    # SESION DE CAJA
    url(r'^caja', caja.view, name='caja'),

    # GESTION DE PRODUCTOS
    url(r'^productos$', productos.view, name='productos'),

    # SERVICIOS
    url(r'^servicios$', servicios.view, name='servicios'),

    # PAQUETES
    url(r'^paquetes$', paquetes.view, name='paquetes'),

    # SESIONES
    url(r'^sesiones$', sesiones.view, name='sesiones'),

    # ORDENES DE SERVICIOS
    url(r'^ordenes$', ordenes.view, name='ordenes'),

    # CLIENTES
    url(r'^clientes$', clientes.view, name='clientes'),

    # PANEL CLIENTES
    url(r'^panelclientes$', panelclientes.view, name='panelclientes'),

    # PANEL COLABORADORES
    url(r'^panelcolaborador$', panelcolaborador.view, name='panelcolaborador'),

    # PROVEEDORES
    url(r'^proveedores$', proveedores.view, name='proveedores'),

    # CAJEROS
    url(r'^cajeros$', cajeros.view, name='cajeros'),

    # CONSULTAS
    url(r'^consultas$', consultas.view, name='consultas'),

    # ESTADISTICAS Y GRAFICOS
    url(r'^estadisticas$', estadisticas.view, name='estadisticas'),

]

# Static
urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)

# Media
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

inv/forms.py
import os

from django import forms
from django.forms import DateTimeInput

from inv.models import (UnidadMedida, TipoProducto, TipoDocumento, Banco, TipoTarjetaBanco, ProcesadorPagoTarjeta,
                        FormaDePago, Area, TipoCabello, TipoPiel, TipoServicio, Producto, Servicio, Proveedor,
                        TIPOS_PAQUETES, Factura, Paquete, Cliente, Colaborador)
from spa.settings import (TIPO_CLIENTE_CORPORATIVO, TIPO_PRODUCTO_PARA_VENTA, TIPO_PRODUCTO_PARA_CONSUMO,
                          TIPO_PRODUCTO_RECIBIDO_CONSIGNACION, VALORACION_EXCELENTE, VALORACION_MUYBIEN, 
                          VALORACION_BIEN, VALORACION_REGULAR, VALORACION_MAL, PAQUETE_PROMOCIONAL, PAQUETE_SERVICIO, 
                          TIPO_CLIENTE_NORMAL, TIPO_CLIENTE_VIP)


def deshabilitar_campo(form, campo):
    form.fields[campo].widget.attrs['readonly'] = True
    form.fields[campo].widget.attrs['disabled'] = True


class ExtFileField(forms.FileField):
    """
    * max_upload_size - a number indicating the maximum file size allowed for upload.
            500Kb - 524288
            1MB - 1048576
            2.5MB - 2621440
            5MB - 5242880
            10MB - 10485760
            20MB - 20971520
            50MB - 5242880
            100MB 104857600
            250MB - 214958080
            500MB - 429916160
    t = ExtFileField(ext_whitelist=(".pdf", ".txt"), max_upload_size=)
    """

    def __init__(self, *args, **kwargs):
        ext_whitelist = kwargs.pop("ext_whitelist")
        self.ext_whitelist = [i.lower() for i in ext_whitelist]
        self.max_upload_size = kwargs.pop("max_upload_size")
        super(ExtFileField, self).__init__(*args, **kwargs)

    def clean(self, *args, **kwargs):
        upload = super(ExtFileField, self).clean(*args, **kwargs)
        if upload:
            size = upload.size
            filename = upload.name
            ext = os.path.splitext(filename)[1]
            ext = ext.lower()

            if size == 0 or ext not in self.ext_whitelist or size > self.max_upload_size:
                raise forms.ValidationError("Tipo de fichero o tamanno no permitido!")


class ProductoForm(forms.Form):
    TIPOS_DESTINOS_PRODUCTO = (
        (TIPO_PRODUCTO_PARA_VENTA, 'VENTA'),
        (TIPO_PRODUCTO_PARA_CONSUMO, 'CONSUMO'),
        (TIPO_PRODUCTO_RECIBIDO_CONSIGNACION, 'RECIBIDO CONSIGNACIÓN')
    )
    tipo = forms.ChoiceField(choices=TIPOS_DESTINOS_PRODUCTO, initial=TIPO_PRODUCTO_PARA_VENTA,
                             widget=forms.Select(attrs={'class': 'imp-50', 'separador': 'Datos Generales'}))
    tipoproducto = forms.ModelChoiceField(TipoProducto.objects, label='Categoría',
                                          widget=forms.Select(attrs={'class': 'imp-50'}))
    codigo = forms.CharField(label='Código', required=False, widget=forms.TextInput(attrs={'class': 'imp-30'}))
    descripcion = forms.CharField(label='Descripción', widget=forms.Textarea({'rows': '2'}))
    unidadmedida = forms.ModelChoiceField(UnidadMedida.objects, label='UM',
                                          widget=forms.Select(attrs={'class': 'imp-30'}))
    alias = forms.CharField(max_length=20, label='Alias', required=False,
                            widget=forms.TextInput(attrs={'class': 'imp-30'}))
    codigobarra = forms.CharField(max_length=20, label='Código Barra', required=False,
                                  widget=forms.TextInput(attrs={'class': 'imp-30'}))
    minimo = forms.FloatField(initial='0.00', label='Cantidad Mínima', required=False,
                              widget=forms.TextInput(attrs={'class': 'imp-20 atright'}))
    con_iva = forms.BooleanField(initial=True, required=False, label='Con IVA?')
    precio = forms.FloatField(initial='0.00', label='Referencial', required=False,
                              widget=forms.TextInput(attrs={'class': 'imp-20 atright', 
                                                            'separador': 'Configurar Precios'}))
    precio_cliente_normal = forms.FloatField(initial='0.00', label='Clientes Normales', required=False,
                                             widget=forms.TextInput(attrs={'class': 'imp-20 atright'}))
    precio_cliente_corporativo = forms.FloatField(initial='0.00', label='Clientes Corporativos', required=False,
                                                  widget=forms.TextInput(attrs={'class': 'imp-20 atright'}))
    precio_cliente_vip = forms.FloatField(initial='0.00', label='Clientes Vip', required=False,
                                          widget=forms.TextInput(attrs={'class': 'imp-20 atright'}))

    def for_editproducto(self):
        self.fields['tipo'].widget.attrs['readonly'] = True
        self.fields['codigo'].widget.attrs['readonly'] = True
        self.fields['tipoproducto'].widget.attrs['readonly'] = True


class ServicioForm(forms.Form):
    tiposervicio = forms.ModelChoiceField(TipoServicio.objects, label='Categoría',
                                          widget=forms.Select(attrs={'class': 'imp-50'}))
    codigo = forms.CharField(label='Código', required=False, widget=forms.TextInput(attrs={'class': 'imp-30'}))
    descripcion = forms.CharField(label='Descripción', widget=forms.Textarea({'rows': '2'}))
    unidadmedida = forms.ModelChoiceField(UnidadMedida.objects, label='UM',
                                          widget=forms.Select(attrs={'class': 'imp-30'}))
    alias = forms.CharField(max_length=20, label='Alias', required=False,
                            widget=forms.TextInput(attrs={'class': 'imp-30'}))
    con_iva = forms.BooleanField(initial=True, required=False, label='Con IVA?')
    costo_estandar = forms.FloatField(initial='0.00', label='Costo estándar', required=False,
                                      widget=forms.TextInput(attrs={'class': 'imp-20 atright'}))
    precio = forms.FloatField(initial='0.00', label='Referencial', required=False,
                              widget=forms.TextInput(attrs={'class': 'imp-20 atright', 
                                                            'separador': 'Configurar Precios'}))
    precio_cliente_normal = forms.FloatField(initial='0.00', label='Clientes Normales', required=False,
                                             widget=forms.TextInput(attrs={'class': 'imp-20 atright'}))
    precio_cliente_corporativo = forms.FloatField(initial='0.00', label='Clientes Corporativos', required=False,
                                                  widget=forms.TextInput(attrs={'class': 'imp-20 atright'}))
    precio_cliente_vip = forms.FloatField(initial='0.00', label='Clientes Vip', required=False,
                                          widget=forms.TextInput(attrs={'class': 'imp-20 atright'}))

    def for_edit(self):
        self.fields['codigo'].widget.attrs['readonly'] = True
        self.fields['tiposervicio'].widget.attrs['readonly'] = True


class RecetaForm(forms.Form):
    producto = forms.ModelChoiceField(Producto.objects, label='Producto')

    def for_receta(self, servicio):
        self.fields['producto'].queryset = Producto.objects.filter(tipo=TIPO_PRODUCTO_PARA_CONSUMO).exclude(receta__servicio=servicio)


class PaqueteProductoForm(forms.Form):
    producto = forms.ModelChoiceField(Producto.objects, label='Producto',
                                      widget=forms.Select(attrs={'class': 'myselect2'}))

    def for_paquete(self, paquete):
        self.fields['producto'].queryset = Producto.objects.filter(tipo=TIPO_PRODUCTO_PARA_VENTA).exclude(paqueteproducto__paquete=paquete)


class PaqueteServicioForm(forms.Form):
    servicio = forms.ModelChoiceField(Servicio.objects, label='Servicio',
                                      widget=forms.Select(attrs={'class': 'myselect2'}))

    def for_paquete(self, paquete):
        self.fields['servicio'].queryset = Servicio.objects.all().exclude(paqueteservicio__paquete=paquete)


class ServicioFuturoForm(forms.Form):
    servicio = forms.ModelChoiceField(Servicio.objects, label='Servicio Futuro',
                                      widget=forms.Select(attrs={'class': 'myselect2'}))
    fecha = forms.DateField(label=u"Fecha", input_formats=['%d-%m-%Y'],
                            widget=DateTimeInput(format='%d-%m-%Y', attrs={'class': 'selectorfecha'}))

    def for_serviciofuturo(self, orden):
        self.fields['servicio'].queryset = Servicio.objects.all().exclude(serviciofuturo__orden=orden)


class PaqueteForm(forms.Form):
    codigo = forms.CharField(label='Código', required=False,
                             widget=forms.TextInput(attrs={'class': 'imp-30'}))
    descripcion = forms.CharField(label='Descripción', widget=forms.TextInput())
    alias = forms.CharField(max_length=20, label='Alias', required=False,
                            widget=forms.TextInput(attrs={'class': 'imp-30'}))
    tipo = forms.ChoiceField(choices=TIPOS_PAQUETES, initial=PAQUETE_PROMOCIONAL,
                             widget=forms.Select(attrs={'class': 'imp-30'}))
    sesiones = forms.IntegerField(initial=2, label='Sesiones',
                                  widget=forms.TextInput(attrs={'class': 'imp-10 atright'}))


class ProveedorForm(forms.Form):
    nombre = forms.CharField(max_length=200, label='Razón Social')
    identificacion = forms.CharField(max_length=200, label='Identificación', required=False)
    alias = forms.CharField(max_length=100, label='Alias', required=False)
    pais = forms.CharField(max_length=200, label='Pais', required=False)
    direccion = forms.CharField(max_length=200, label='Dirección', required=False)
    telefono = forms.CharField(max_length=100, label='Teléfono', required=False)
    celular = forms.CharField(max_length=100, label='Celular', required=False)
    email = forms.CharField(max_length=200, label='Email', required=False)
    fax = forms.CharField(max_length=100, label='Fax', required=False)
    logo = ExtFileField(label='Seleccione Logo', required=False,

templates/ordenes/add_serviciofuturo.html
{% extends "ajaxformbs.html" %}
{% block extraheading %}
    <script>
        $(function(){

            $("#id_servicio").addClass("validate[required]");

            $("#id_fecha").datepicker({format:"dd-mm-yyyy"}).on('changeDate', function(ev){ $(this).datepicker('hide'); });

        });
    </script>
{% endblock %}
{% block titulo %}{{ title }}{% endblock %}
{% block formaction %}/ordenes{% endblock %}
{% block formdestination %}/ordenes?action=serviciosfuturos&id={{ orden.id }}{% endblock %}
{% block formextra %}
    <input type='hidden' name='action' value='add_serviciofuturo'/>
    <input type='hidden' name='id' value='{{ orden.id }}'/>
{% endblock %}
{% block formback %}/ordenes?action=serviciosfuturos&id={{ orden.id }}{% endblock %}
{% block buttonname %}Guardar{% endblock %}

templates/ordenes/delete.html
{% extends "ajaxdeletebs.html" %}
{% block extraheading %}
    <script>
    $(function () {

    });
    </script>
{% endblock %}
{% block titulo %}{{ title }}{% endblock %}
{% block formback %}/ordenes{% endblock %}
{% block formdestination %}/ordenes{% endblock %}
{% block formaction %}/ordenes{% endblock %}
{% block formactionvalue %}delete{% endblock %}
{% block formobjectid %}{{ orden.id }}{% endblock %}
{% block formobjectname %}la orden de servicio #<b>{{ orden.repr_id }}</b>{% endblock %}

templates/ordenes/delete_serviciofuturo.html
{% extends "ajaxdeletebs.html" %}
{% block extraheading %}
    <script>
    $(function () {
    });
    </script>
{% endblock %}
{% block titulo %}{{ title }}{% endblock %}
{% block formback %}/ordenes?action=serviciosfuturos&id={{ orden.id }}{% endblock %}
{% block formdestination %}/ordenes?action=serviciosfuturos&id={{ orden.id }}{% endblock %}
{% block formaction %}/ordenes{% endblock %}
{% block formactionvalue %}delete_serviciofuturo{% endblock %}
{% block formobjectid %}{{ servicio_futuro.id }}{% endblock %}
{% block formobjectname %}el servicio futuro <b>{{ servicio_futuro.servicio }}</b> de la orden <b>{{ orden.repr_id }}</b>{% endblock %}

templates/ordenes/detalles.html
<table class="table table-bordered">
    <thead>
    <tr>
        <th style="width: 100px">Tipo</th>
        <th style="width: 100px">C&oacute;digo</th>
        <th>Descripci&oacute;n</th>
        <th style="width: 100px">Categor&iacute;a</th>
        <th style="width: 60px; text-align: center">Cant.</th>
        <th style="width: 80px; text-align: center">Precio</th>
        <th style="width: 80px; text-align: center">Valor</th>
    </tr>
    </thead>
    <tbody>
    {% for d in detalles %}
        <tr class="normal11">
            <td>{% if d.producto %}PRODUCTO{% else %}SERVICIO{% endif %}</td>
            <td>{% if d.producto %}{{ d.producto.codigo }}{% else %}{{ d.servicio.codigo }}{% endif %}</td>
            <td>{% if d.producto %}{{ d.producto.descripcion }}{% else %}{{ d.servicio.descripcion }}{% endif %}</td>
            <td>{% if d.producto %}{{ d.producto.tipoproducto.nombre }}{% else %}{{ d.servicio.tiposervicio.nombre }}{% endif %}</td>
            <td style="text-align: center">{{ d.cantidad|floatformat:0 }}</td>
            <td style="text-align: right">${{ d.precio|floatformat:2 }}</td>
            <td style="text-align: right">${{ d.valor|floatformat:2 }}</td>
        </tr>
    {% endfor %}
    </tbody>
    <tfoot>
    <tr>
        <td colspan="6">Iva: <b>${{ orden.iva|floatformat:2 }}</b> &nbsp; Total: <b>${{ orden.total|floatformat:2 }}</b></td>
        <td style="text-align: right; font-weight: bold">$ {{ orden.subtotal|floatformat:2 }}</td>
    </tr>
    </tfoot>
</table>

{% if orden.observaciones %}
    <span><b>Observaciones: </b> {{ orden.observaciones }}</span>
{% endif %}

templates/ordenes/serviciosfuturos.html
{% extends "basebs.html" %}
{% load humanize %}
{% block heading %}
    <script>
        $(function() {

        });
    </script>
{% endblock %}

{% block canvas %}
    <div class='row-fluid'>
        <div class='span12'>
            <div class="panel panel-turquesa">
                <div class="panel-heading">
                    Servicios Futuros - Cliente {{ orden.cliente }}
                </div>
                <div class="panel-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th style="width: 170px">Fecha</th>
                                <th style="width: 230px">C&oacute;digo</th>
                                <th>Descripci&oacute;n</th>
                                <th style="width: 100px"></th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for sf in servicios_futuros %}
                            <tr>
                                <td>{{ sf.fecha|date:'d-m-Y' }}</td>
                                <td>{{ sf.servicio.codigo }}</td>
                                <td>{{ sf.servicio.descripcion }}</td>
                                <td style="text-align: center">
                                    <a href="/ordenes?action=delete_serviciofuturo&id={{ sf.id }}" class="btn btn-danger btn-small btn-form"><i class="fa fa-times tl" title="Eliminar"></i> </a>
                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="5"><i>No existen servicios futuros para el cliente</i></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="row-fluid">
                <a href="/ordenes?action=add_serviciofuturo&id={{ orden.id }}" class='btn btn-turquesa btn-form'><i class="fa fa-plus"></i> Adicionar</a>
                <a href="/ordenes" class='btn btn-default btn-form'><i class="fa fa-arrow-left"></i> Atr&aacute;s</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/ordenes/view.html
{% extends "basebs.html" %}
{% load humanize %}
{% block heading %}
    <script>
        $(function() {

            //Detalles orden de servicio
            $("#detalle_orden .btn-aceptar").click(function(){
                $("#detalle_orden").modal("hide");
                return false;
            });

            $(".detalleorden").click(function() {
                var ordenid = $(this).attr("ordenid");
                var num_orden = $(this).attr("numorden");
                var nombre_colaborador = $(this).attr("nombrecolaborador");
                $.get("/ordenes", {'action':'detalle_orden', 'id': ordenid}, function(data) {
                    $("#num_orden").html(num_orden);
                    $("#colaborador_orden").html(nombre_colaborador);
                    $("#detalle_orden .modal-body").html(data);
                    $("#detalle_orden").modal({"backdrop":"static", "width": "1100px"}).modal("show");
                }, "html");
                return false;
            });

            $("#clientesel").change(function(){
                bloqueointerface();
                var cid = $(this).val();
                location.href = '/ordenes?c='+cid;
            });
        });
    </script>
{% endblock %}
{% block canvas %}
    <div class='row-fluid'>
        <div class="span10">
            <form class="form-search">
                <input class='searchinput input-xlarge search-query' type='text' id='searchfield' value='{{ search }}'/>
                <a href="#" id='search' class='btn btn-success tl' title="Buscar"><i class="fa fa-search"></i> </a>
                {% if search %}
                    <a href="/ordenes" id='allresults' class='btn btn-info tr' title="Ver todos"><i class="fa fa-list"></i></a>
                {% endif %}
            </form>
        </div>
        <div class="span2">
            <form>
                <label for="clientesel"></label>
                <select id='clientesel'>
                    <option value='0'>-----</option>
                    {% for c in clientes %}
                        <option value="{{ c.id }}" {% ifequal clienteid c.id %}selected="selected"{% endifequal %}>{{ c.nombre }}</option>
                    {% endfor %}
                </select>
            </form>
        </div>
    </div>
    <div class='row-fluid'>
        <div class='span12'>
            <div class="panel panel-turquesa">
                <div class="panel-heading">
                    Mis Ordenes de Servicios
                </div>
                <div class="panel-body">
                    <table class='table table-bordered' cellpadding="0" cellspacing="0">
                        <thead>
                        <tr>
                            <th style="width: 100px">Orden</th>
                            <th style="width: 120px">Fecha</th>
                            <th>Cliente</th>
{#                            <th style="width: 80px; text-align: center">SubTotal</th>#}
{#                            <th style="width: 80px; text-align: center">IVA</th>#}
{#                            <th style="width: 80px; text-align: center">Total</th>#}
                            <th style="width: 80px; text-align: center">Prod.</th>
                            <th style="width: 80px; text-align: center">Serv.</th>
                            <th style="width: 100px; text-align: center">Factura Asig.</th>
                            <th style="width: 100px; text-align: center">Fecha Asig.</th>
                            <th style="width: 100px"></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for orden in ordenes %}
                            <tr>
                                <td class="larger"> {{ orden.repr_id }}</td>
                                <td class="larger"> {{ orden.fecha|date:'d-m-Y' }}</td>
                                <td class="larger">{{ orden.cliente }} </td>
{#                                <td style="text-align: right"> ${{ orden.subtotal|floatformat:2 }}</td>#}
{#                                <td style="text-align: right"> ${{ orden.iva|floatformat:2 }}</td>#}
{#                                <td style="text-align: right"> ${{ orden.total|floatformat:2 }}</td>#}
                                <td style="text-align: center" class="larger">{{ orden.cantidad_productos|floatformat:0 }}</td>
                                <td style="text-align: center" class="larger">{{ orden.cantidad_servicios|floatformat:0 }}</td>
                                <td style="text-align: center">{{ orden.factura_asignada.numero|default_if_none:'' }}</td>
                                <td style="text-align: center">{{ orden.fecha_asignada|date:'d-m-Y' }}</td>
                                <td>
                                    <div class="btn-group">
                                        <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#">
                                            Acciones
                                            <span class="caret"></span>
                                        </a>
                                        <ul class="dropdown-menu pull-right list-group">
                                            <li><a class="detalleorden" href='#' ordenid="{{ orden.id }}" numorden="{{ orden.repr_id }}" nombrecolaborador="{{ orden.colaborador.nombre }}"><i class="fa fa-list"></i> Detalles</a></li>
                                            <li><a href='/ordenes?action=serviciosfuturos&id={{ orden.id }}' class="btn-form"><i class="fa fa-table"></i> Servicios Futuros</a></li>
                                            {% if not orden.en_uso %}
                                                <li class="divider"></li>
                                                <li><a href='/ordenes?action=delete&id={{ orden.id }}' class="btn-form"><i class="fa fa-times"></i> Eliminar</a></li>
                                            {% endif %}
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="15">
                                    NO EXISTEN ORDENES DE SERVICIOS REGISTRADAS EN EL SISTEMA
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="row-fluid">
                <a href="/ordenes?action=add" class='btn btn-turquesa btn-form'><i class="fa fa-plus"></i> Adicionar</a>
            </div>
            <div class='row-fluid'>
                {% if paging.num_pages > 20 %}
                    <div class='pagination'>
                        <ul>
                            {% if paging.primera_pagina %}
                                <li><a href="/ordenes?page=1">1</a></li>
                                <li><a href="/ordenes?page={{ paging.ellipsis_izquierda }}" class="active">...</a></li>
                            {% endif %}
                            {% for pagenumber in paging.paginas %}
                                <li {% ifequal pagenumber page.number %}class='active'{% endifequal %}><a href="/ordenes?action=consulta_solicitudes_vendedores&page={{ pagenumber }}">{{ pagenumber }}</a></li>
                            {% endfor %}
                            {% if paging.ultima_pagina %}
                                <li><a href="/ordenes?page={{ paging.ellipsis_derecha }}" class="active">...</a></li>
                                <li><a href="/ordenes?page={{ paging.num_pages }}">{{ paging.num_pages }}</a></li>
                            {% endif %}
                        </ul>
                    </div>
                {% else %}
                    <div class='pagination'>
                        <ul>
                            {% for pagenumber in paging.page_range %}
                                <li {% ifequal pagenumber page.number %}class='active'{% endifequal %}><a href="/ordenes?{% if search %}s={{ search }}&{% endif %}page={{ pagenumber }}">{{ pagenumber }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

{% block moreblock %}
    <div class="modal fade static" id="detalle_orden" style="display: none;">
        <div class="modal-header">
            <h3 class="paneltitle">Detalles de orden de servicio #<span id="num_orden"></span> generada por el colaborador: <span id="colaborador_orden"></span></h3>
        </div>
        <div class="modal-body"></div>
        <div class="modal-footer">
            <div style="float: right">
                <a href="#" class="btn btn-primary  btn-aceptar"><i class="fa fa-check"></i> Aceptar</a>
            </div>
        </div>
    </div>
{% endblock %}