spa/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from inv import (views, ventas, compras, pagos, caja, productos, servicios, paquetes, sesiones, ordenes, clientes,
                 panelclientes, panelcolaborador, proveedores, cajeros, consultas, estadisticas)

from spa.settings import STATIC_URL, STATIC_ROOT, MEDIA_URL, MEDIA_ROOT

urlpatterns = [

    # Admin
    url(r'^admin/', include(admin.site.urls)),

    # Home
    url(r'^$', views.index, name='index'),

    # Login
    url(r'^login$', views.login_user, name='login_user'),

    # Logout
    url(r'^logout$', views.logout_user, name='logout_user'),

    # Change passw
    url(r'^pass$', views.passwd, name='change_password'),

    # Get Data API
    url(r'^get_data$', views.get_data, name='get_data'),

    # Subir Video
    url(r'^subir_video$', views.subir_video, name='subir_video'),

    # VENTAS
    url(r'^ventas$', ventas.view, name='ventas'),

    # COMPRAS
    url(r'^compras$', compras.view, name='compras'),

    # PAGOS
    url(r'^pagos$', pagos.view, name='pagos'),

    # SESION DE CAJA
    url(r'^caja', caja.view, name='caja'),

    # GESTION DE PRODUCTOS
    url(r'^productos$', productos.view, name='productos'),

    # SERVICIOS
    url(r'^servicios$', servicios.view, name='servicios'),

    # PAQUETES
    url(r'^paquetes$', paquetes.view, name='paquetes'),

    # SESIONES
    url(r'^sesiones$', sesiones.view, name='sesiones'),

    # ORDENES DE SERVICIOS
    url(r'^ordenes$', ordenes.view, name='ordenes'),

    # CLIENTES
    url(r'^clientes$', clientes.view, name='clientes'),

    # PANEL CLIENTES
    url(r'^panelclientes$', panelclientes.view, name='panelclientes'),

    # PANEL COLABORADORES
    url(r'^panelcolaborador$', panelcolaborador.view, name='panelcolaborador'),

    # PROVEEDORES
    url(r'^proveedores$', proveedores.view, name='proveedores'),

    # CAJEROS
    url(r'^cajeros$', cajeros.view, name='cajeros'),

    # CONSULTAS
    url(r'^consultas$', consultas.view, name='consultas'),

    # ESTADISTICAS Y GRAFICOS
    url(r'^estadisticas$', estadisticas.view, name='estadisticas'),

]

# Static
urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)

# Media
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

inv/forms.py
import os

from django import forms
from django.forms import DateTimeInput

from inv.models import (UnidadMedida, TipoProducto, TipoDocumento, Banco, TipoTarjetaBanco, ProcesadorPagoTarjeta,
                        FormaDePago, Area, TipoCabello, TipoPiel, TipoServicio, Producto, Servicio, Proveedor,
                        TIPOS_PAQUETES, Factura, Paquete, Cliente, Colaborador)
from spa.settings import (TIPO_CLIENTE_CORPORATIVO, TIPO_PRODUCTO_PARA_VENTA, TIPO_PRODUCTO_PARA_CONSUMO,
                          TIPO_PRODUCTO_RECIBIDO_CONSIGNACION, VALORACION_EXCELENTE, VALORACION_MUYBIEN, 
                          VALORACION_BIEN, VALORACION_REGULAR, VALORACION_MAL, PAQUETE_PROMOCIONAL, PAQUETE_SERVICIO, 
                          TIPO_CLIENTE_NORMAL, TIPO_CLIENTE_VIP)


def deshabilitar_campo(form, campo):
    form.fields[campo].widget.attrs['readonly'] = True
    form.fields[campo].widget.attrs['disabled'] = True


class ExtFileField(forms.FileField):
    """
    * max_upload_size - a number indicating the maximum file size allowed for upload.
            500Kb - 524288
            1MB - 1048576
            2.5MB - 2621440
            5MB - 5242880
            10MB - 10485760
            20MB - 20971520
            50MB - 5242880
            100MB 104857600
            250MB - 214958080
            500MB - 429916160
    t = ExtFileField(ext_whitelist=(".pdf", ".txt"), max_upload_size=)
    """

    def __init__(self, *args, **kwargs):
        ext_whitelist = kwargs.pop("ext_whitelist")
        self.ext_whitelist = [i.lower() for i in ext_whitelist]
        self.max_upload_size = kwargs.pop("max_upload_size")
        super(ExtFileField, self).__init__(*args, **kwargs)

    def clean(self, *args, **kwargs):
        upload = super(ExtFileField, self).clean(*args, **kwargs)
        if upload:
            size = upload.size
            filename = upload.name
            ext = os.path.splitext(filename)[1]
            ext = ext.lower()

            if size == 0 or ext not in self.ext_whitelist or size > self.max_upload_size:
                raise forms.ValidationError("Tipo de fichero o tamanno no permitido!")


class ProductoForm(forms.Form):
    TIPOS_DESTINOS_PRODUCTO = (
        (TIPO_PRODUCTO_PARA_VENTA, 'VENTA'),
        (TIPO_PRODUCTO_PARA_CONSUMO, 'CONSUMO'),
        (TIPO_PRODUCTO_RECIBIDO_CONSIGNACION, 'RECIBIDO CONSIGNACIÓN')
    )
    tipo = forms.ChoiceField(choices=TIPOS_DESTINOS_PRODUCTO, initial=TIPO_PRODUCTO_PARA_VENTA,
                             widget=forms.Select(attrs={'class': 'imp-50', 'separador': 'Datos Generales'}))
    tipoproducto = forms.ModelChoiceField(TipoProducto.objects, label='Categoría',
                                          widget=forms.Select(attrs={'class': 'imp-50'}))
    codigo = forms.CharField(label='Código', required=False, widget=forms.TextInput(attrs={'class': 'imp-30'}))
    descripcion = forms.CharField(label='Descripción', widget=forms.Textarea({'rows': '2'}))
    unidadmedida = forms.ModelChoiceField(UnidadMedida.objects, label='UM',
                                          widget=forms.Select(attrs={'class': 'imp-30'}))
    alias = forms.CharField(max_length=20, label='Alias', required=False,
                            widget=forms.TextInput(attrs={'class': 'imp-30'}))
    codigobarra = forms.CharField(max_length=20, label='Código Barra', required=False,
                                  widget=forms.TextInput(attrs={'class': 'imp-30'}))
    minimo = forms.FloatField(initial='0.00', label='Cantidad Mínima', required=False,
                              widget=forms.TextInput(attrs={'class': 'imp-20 atright'}))
    con_iva = forms.BooleanField(initial=True, required=False, label='Con IVA?')
    precio = forms.FloatField(initial='0.00', label='Referencial', required=False,
                              widget=forms.TextInput(attrs={'class': 'imp-20 atright', 
                                                            'separador': 'Configurar Precios'}))
    precio_cliente_normal = forms.FloatField(initial='0.00', label='Clientes Normales', required=False,
                                             widget=forms.TextInput(attrs={'class': 'imp-20 atright'}))
    precio_cliente_corporativo = forms.FloatField(initial='0.00', label='Clientes Corporativos', required=False,
                                                  widget=forms.TextInput(attrs={'class': 'imp-20 atright'}))
    precio_cliente_vip = forms.FloatField(initial='0.00', label='Clientes Vip', required=False,
                                          widget=forms.TextInput(attrs={'class': 'imp-20 atright'}))

    def for_editproducto(self):
        self.fields['tipo'].widget.attrs['readonly'] = True
        self.fields['codigo'].widget.attrs['readonly'] = True
        self.fields['tipoproducto'].widget.attrs['readonly'] = True


class ServicioForm(forms.Form):
    tiposervicio = forms.ModelChoiceField(TipoServicio.objects, label='Categoría',
                                          widget=forms.Select(attrs={'class': 'imp-50'}))
    codigo = forms.CharField(label='Código', required=False, widget=forms.TextInput(attrs={'class': 'imp-30'}))
    descripcion = forms.CharField(label='Descripción', widget=forms.Textarea({'rows': '2'}))
    unidadmedida = forms.ModelChoiceField(UnidadMedida.objects, label='UM',
                                          widget=forms.Select(attrs={'class': 'imp-30'}))
    alias = forms.CharField(max_length=20, label='Alias', required=False,
                            widget=forms.TextInput(attrs={'class': 'imp-30'}))
    con_iva = forms.BooleanField(initial=True, required=False, label='Con IVA?')
    costo_estandar = forms.FloatField(initial='0.00', label='Costo estándar', required=False,
                                      widget=forms.TextInput(attrs={'class': 'imp-20 atright'}))
    precio = forms.FloatField(initial='0.00', label='Referencial', required=False,
                              widget=forms.TextInput(attrs={'class': 'imp-20 atright', 
                                                            'separador': 'Configurar Precios'}))
    precio_cliente_normal = forms.FloatField(initial='0.00', label='Clientes Normales', required=False,
                                             widget=forms.TextInput(attrs={'class': 'imp-20 atright'}))
    precio_cliente_corporativo = forms.FloatField(initial='0.00', label='Clientes Corporativos', required=False,
                                                  widget=forms.TextInput(attrs={'class': 'imp-20 atright'}))
    precio_cliente_vip = forms.FloatField(initial='0.00', label='Clientes Vip', required=False,
                                          widget=forms.TextInput(attrs={'class': 'imp-20 atright'}))

    def for_edit(self):
        self.fields['codigo'].widget.attrs['readonly'] = True
        self.fields['tiposervicio'].widget.attrs['readonly'] = True


class RecetaForm(forms.Form):
    producto = forms.ModelChoiceField(Producto.objects, label='Producto')

    def for_receta(self, servicio):
        self.fields['producto'].queryset = Producto.objects.filter(tipo=TIPO_PRODUCTO_PARA_CONSUMO).exclude(receta__servicio=servicio)


class PaqueteProductoForm(forms.Form):
    producto = forms.ModelChoiceField(Producto.objects, label='Producto',
                                      widget=forms.Select(attrs={'class': 'myselect2'}))

    def for_paquete(self, paquete):
        self.fields['producto'].queryset = Producto.objects.filter(tipo=TIPO_PRODUCTO_PARA_VENTA).exclude(paqueteproducto__paquete=paquete)


class PaqueteServicioForm(forms.Form):
    servicio = forms.ModelChoiceField(Servicio.objects, label='Servicio',
                                      widget=forms.Select(attrs={'class': 'myselect2'}))

    def for_paquete(self, paquete):
        self.fields['servicio'].queryset = Servicio.objects.all().exclude(paqueteservicio__paquete=paquete)


class ServicioFuturoForm(forms.Form):
    servicio = forms.ModelChoiceField(Servicio.objects, label='Servicio Futuro',
                                      widget=forms.Select(attrs={'class': 'myselect2'}))
    fecha = forms.DateField(label=u"Fecha", input_formats=['%d-%m-%Y'],
                            widget=DateTimeInput(format='%d-%m-%Y', attrs={'class': 'selectorfecha'}))

    def for_serviciofuturo(self, orden):
        self.fields['servicio'].queryset = Servicio.objects.all().exclude(serviciofuturo__orden=orden)


class PaqueteForm(forms.Form):
    codigo = forms.CharField(label='Código', required=False,
                             widget=forms.TextInput(attrs={'class': 'imp-30'}))
    descripcion = forms.CharField(label='Descripción', widget=forms.TextInput())
    alias = forms.CharField(max_length=20, label='Alias', required=False,
                            widget=forms.TextInput(attrs={'class': 'imp-30'}))
    tipo = forms.ChoiceField(choices=TIPOS_PAQUETES, initial=PAQUETE_PROMOCIONAL,
                             widget=forms.Select(attrs={'class': 'imp-30'}))
    sesiones = forms.IntegerField(initial=2, label='Sesiones',
                                  widget=forms.TextInput(attrs={'class': 'imp-10 atright'}))


class ProveedorForm(forms.Form):
    nombre = forms.CharField(max_length=200, label='Razón Social')
    identificacion = forms.CharField(max_length=200, label='Identificación', required=False)
    alias = forms.CharField(max_length=100, label='Alias', required=False)
    pais = forms.CharField(max_length=200, label='Pais', required=False)
    direccion = forms.CharField(max_length=200, label='Dirección', required=False)
    telefono = forms.CharField(max_length=100, label='Teléfono', required=False)
    celular = forms.CharField(max_length=100, label='Celular', required=False)
    email = forms.CharField(max_length=200, label='Email', required=False)
    fax = forms.CharField(max_length=100, label='Fax', required=False)
    logo = ExtFileField(label='Seleccione Logo', required=False,

templates/paquetes/add.html
{% extends "ajaxformbs.html" %}
{% block extraheading %}
    <script>
        $(function(){
            $("#id_codigo, #id_descripcion, #id_unidadmedida, #id_tiposervicio, #id_sesiones, #id_precio, #id_precio_cliente_normal, #id_precio_cliente_corporativo, #id_precio_cliente_vip").addClass("validate[required]");

            $("#id_sesiones").blur(function(){
                numerico($(this), 1, 0, 0);
            });

            //Activar pestana
            $("#pestana14").addClass('current');
        });
    </script>
{% endblock %}
{% block titulo %}{{ title }}{% endblock %}
{% block formaction %}/paquetes{% endblock %}
{% block formdestination %}/paquetes{% endblock %}
{% block formextra %}
    <input type='hidden' name='action' value='add'/>
{% endblock %}
{% block formback %}/paquetes{% endblock %}
{% block buttonname %}Guardar{% endblock %}

templates/paquetes/addelementoproducto.html
{% extends "ajaxformbs.html" %}
{% block extraheading %}
    <script>
        $(function(){
            $("#id_producto").addClass("validate[required]");

            //Activar pestana
            $("#pestana14").addClass('current');
        });
    </script>
{% endblock %}
{% block titulo %}{{ title }}{% endblock %}
{% block formwidth %}form-m{% endblock %}
{% block formaction %}/paquetes{% endblock %}
{% block formdestination %}/paquetes?action=elementos&id={{ paquete.id }}{% endblock %}
{% block formextra %}
    <input type='hidden' name='action' value='addelementoproducto'/>
    <input type='hidden' name='id' value='{{ paquete.id }}'/>
{% endblock %}
{% block formback %}/paquetes?action=elementos&id={{ paquete.id }}{% endblock %}
{% block buttonname %}Guardar{% endblock %}

templates/paquetes/addelementoservicio.html
{% extends "ajaxformbs.html" %}
{% block extraheading %}
    <script>
        $(function(){
            $("#id_servicio").addClass("validate[required]");

            //Activar pestana
            $("#pestana14").addClass('current');
        });
    </script>
{% endblock %}
{% block titulo %}{{ title }}{% endblock %}
{% block formaction %}/paquetes{% endblock %}
{% block formdestination %}/paquetes?action=elementos&id={{ paquete.id }}{% endblock %}
{% block formextra %}
    <input type='hidden' name='action' value='addelementoservicio'/>
    <input type='hidden' name='id' value='{{ paquete.id }}'/>
{% endblock %}
{% block formback %}/paquetes?action=elementos&id={{ paquete.id }}{% endblock %}
{% block buttonname %}Guardar{% endblock %}

templates/paquetes/delete.html
{% extends "ajaxdeletebs.html" %}
{% block extraheading %}
    <script>
        $(function(){
            //Activar pestana
            $("#pestana14").addClass('current');
        });
    </script>
{% endblock %}
{% block titulo %}{{ title }}{% endblock %}
{% block formback %}/servicios{% endblock %}
{% block formdestination %}/servicios{% endblock %}
{% block formaction %}/servicios{% endblock %}
{% block formactionvalue %}delete{% endblock %}
{% block formobjectid %}{{ paquete.id }}{% endblock %}
{% block formobjectname %}el paquete: <b>{{ paquete }}</b>{% endblock %}

templates/paquetes/deleteelementoproducto.html
{% extends "ajaxdeletebs.html" %}
{% block extraheading %}
    <script>
        $(function(){
            //Activar pestana
            $("#pestana14").addClass('current');
        });
    </script>
{% endblock %}
{% block titulo %}{{ title }}{% endblock %}
{% block formback %}/paquetes?action=elementos&id={{ paquete.id }}{% endblock %}
{% block formdestination %}/paquetes?action=elementos&id={{ paquete.id }}{% endblock %}
{% block formaction %}/paquetes{% endblock %}
{% block formactionvalue %}deleteelementoproducto{% endblock %}
{% block formobjectid %}{{ paqueteproducto.id }}{% endblock %}
{% block formobjectname %}el producto <b>{{ paqueteproducto.producto.codigo }}</b> del paquete <b>{{ paquete.codigo }}</b>{% endblock %}

templates/paquetes/deleteelementoservicio.html
{% extends "ajaxdeletebs.html" %}
{% block extraheading %}
    <script>
        $(function(){
            //Activar pestana
            $("#pestana14").addClass('current');
        });
    </script>
{% endblock %}
{% block titulo %}{{ title }}{% endblock %}
{% block formback %}/paquetes?action=elementos&id={{ paquete.id }}{% endblock %}
{% block formdestination %}/paquetes?action=elementos&id={{ paquete.id }}{% endblock %}
{% block formaction %}/paquetes{% endblock %}
{% block formactionvalue %}deleteelementoservicio{% endblock %}
{% block formobjectid %}{{ paqueteservicio.id }}{% endblock %}
{% block formobjectname %}el producto <b>{{ paqueteservicio.servicio.codigo }}</b> del paquete <b>{{ paquete.codigo }}</b>{% endblock %}

templates/paquetes/edit.html
{% extends "ajaxformbs.html" %}
{% block extraheading %}
    <script>
        $(function(){
            $("#id_codigo, #id_descripcion, #id_unidadmedida, #id_tiposervicio, #id_precio, #id_precio_cliente_normal, #id_precio_cliente_corporativo, #id_precio_cliente_vip").addClass("validate[required]");

            $("#id_sesiones").blur(function(){
                numerico($(this), 1, 0, 0);
            });

            //Activar pestana
            $("#pestana14").addClass('current');
        });
    </script>
{% endblock %}
{% block titulo %}{{ title }}{% endblock %}
{% block formaction %}/paquetes{% endblock %}
{% block formdestination %}/paquetes{% endblock %}
{% block formextra %}
    <input type='hidden' name='action' value='edit'/>
    <input type='hidden' name='id' value='{{ paquete.id }}'/>
{% endblock %}
{% block formback %}/paquetes{% endblock %}
{% block buttonname %}Guardar{% endblock %}

templates/paquetes/elementos.html
{% extends "basebs.html" %}
{% load humanize %}
{% block heading %}
    <script>
        $(function() {

            $("#porciento_cliente_normal, #porciento_cliente_corporativo, #porciento_cliente_vip").blur(function () {
                numerico($(this), 0, 100, 2);
                calcular_valores();
            });

            calcular_valores = function () {
                var precio_cliente_normal = parseFloat($("#precio_cliente_normal").html());
                var precio_cliente_corporativo = parseFloat($("#precio_cliente_corporativo").html());
                var precio_cliente_vip = parseFloat($("#precio_cliente_vip").html());

                var porciento_cliente_normal = parseFloat($("#porciento_cliente_normal").val());
                var porciento_cliente_corporativo = parseFloat($("#porciento_cliente_corporativo").val());
                var porciento_cliente_vip = parseFloat($("#porciento_cliente_vip").val());

                bloqueointerface();
                $.ajax({
                    type: "POST",
                    url: "/paquetes",
                    data: {
                        'action': 'valor_precios_clientes',
                        'pid': '{{ paquete.id }}',
                        'precio_cliente_normal': precio_cliente_normal,
                        'precio_cliente_corporativo': precio_cliente_corporativo,
                        'precio_cliente_vip': precio_cliente_vip,
                        'porciento_cliente_normal': porciento_cliente_normal,
                        'porciento_cliente_corporativo': porciento_cliente_corporativo,
                        'porciento_cliente_vip': porciento_cliente_vip
                    },
                    success: function(data) {
                        $.unblockUI();
                        if (data.result == 'ok') {
                            $("#valor_cliente_normal").html(data.valor_cliente_normal.toFixed(2));
                            $("#valor_cliente_corporativo").html(data.valor_cliente_corporativo.toFixed(2));
                            $("#valor_cliente_vip").html(data.valor_cliente_vip.toFixed(2));
                        } else {
                            $("#valor_cliente_normal").html("0.00");
                            $("#valor_cliente_corporativo").html("0.00");
                            $("#valor_cliente_vip").html("0.00");
                            smoke.alert(data.mensaje);
                        }
                    },
                    error: function() {
                        $.unblockUI();
                        smoke.alert("Error al enviar los datos.");
                    },
                    dataType: "json"
                });
            };

            //Activar pestana
            $("#pestana14").addClass('current');

        });
    </script>
{% endblock %}
{% block canvas %}
    <div class="row-fluid">
        <div class="span10">
            <h4>{{ title }} {{ paquete.nombre_corto }}</h4>
        </div>
        <div class="span2 atright">
            <a href="/paquetes" class="btn btn-default btn-form"><i class="fa fa-arrow-left"></i> Atr&aacute;s</a>
        </div>
    </div>
    <br/>
    <div class="row-fluid">
        <div class="span12">
            <div class="span6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h5>Productos {% if paquete.cantidad_productos %}({{ paquete.cantidad_productos|floatformat:0 }}){% endif %}</h5>
                    </div>
                    <div class="panel-body">
                        <table class='table table-bordered' cellpadding="0" cellspacing="0">
                            <thead>
                            <tr>
                                <th style="width: 100px">C&oacute;digo</th>
                                <th>Descripci&oacute;n</th>
                                <th style="width: 40px; text-align: center">U.M.</th>
                                <th style="width: 200px">Categor&iacute;a</th>
                                <th style="width: 40px"></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for r in paquete.mis_productos %}
                                <tr>
                                    <td>{{ r.producto.codigo }}</td>
                                    <td>{{ r.producto.descripcion }}</td>
                                    <td style="text-align: center">{{ r.producto.unidadmedida }}</td>
                                    <td>{{ r.producto.tipoproducto.nombre }}</td>
                                    <td style="text-align: center">
                                        <a class="list-group-item btn btn-danger btn-mini btn-form tl" title="Eliminar" href="/paquetes?action=deleteelementoproducto&id={{ r.id }}"><i class="fa fa-times fa-fw"></i></a>
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="10">
                                        No existen productos para el paquete
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                            <tfoot>
                            <tr>
                                <td colspan="10">
                                    <a href="/paquetes?action=addelementoproducto&id={{ paquete.id }}" style="margin: 0.5em" class="btn btn-turquesa btn-form tl" title="Adicionar"><i class="fa fa-plus"></i></a>
                                </td>
                            </tr>
                            </tfoot>

                        </table>
                    </div>
                </div>
            </div>
            <div class="span6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h5>Servicios {% if paquete.cantidad_servicios %}({{ paquete.cantidad_servicios|floatformat:0 }}){% endif %}</h5>
                    </div>
                    <div class="panel-body">
                        <table class='table table-bordered' cellpadding="0" cellspacing="0">
                            <thead>
                            <tr>
                                <th style="width: 100px">C&oacute;digo</th>
                                <th>Descripci&oacute;n</th>
                                <th style="width: 40px; text-align: center">U.M.</th>
                                <th style="width: 200px">Categor&iacute;a</th>
                                <th style="width: 40px"></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for r in paquete.mis_servicios %}
                                <tr>
                                    <td>{{ r.servicio.codigo }}</td>
                                    <td>{{ r.servicio.descripcion }}</td>
                                    <td style="text-align: center">{{ r.servicio.unidadmedida }}</td>
                                    <td>{{ r.servicio.tiposervicio.nombre }}</td>
                                    <td style="text-align: center">
                                        <a class="list-group-item btn btn-danger btn-mini btn-form tl" title="Eliminar" href="/paquetes?action=deleteelementoservicio&id={{ r.id }}"><i class="fa fa-times fa-fw"></i></a>
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="10">
                                        No existen servicios para el paquete
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                            <tfoot>
                            <tr>
                                <td colspan="10">
                                    <a href="/paquetes?action=addelementoservicio&id={{ paquete.id }}" style="margin: 0.5em" class="btn btn-turquesa btn-form tl" title="Adicionar"><i class="fa fa-plus"></i></a>
                                </td>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr/>
    {% if paquete.precio %}
        <div class="row-fluid">
            <div class="span1"></div>
            <div class="span10">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th colspan="10" style="text-align: center">Tabla de precios calculados y porcientos de descuentos por tipos de clientes</th>
                    </tr>
                    <tr>
                        <th style="width: 50px; text-align: center">Prec. Ref</th>
                        <th style="width: 50px; text-align: center">Prec. Norm.</th>
                        <th style="width: 50px; text-align: center">% Prec. Norm.</th>
                        <th style="width: 50px; text-align: center">Valor Norm.</th>
                        <th style="width: 50px; text-align: center">Prec. Corp.</th>
                        <th style="width: 50px; text-align: center">% Prec. Corp.</th>
                        <th style="width: 50px; text-align: center">Valor Corp.</th>
                        <th style="width: 50px; text-align: center">Prec. Vip</th>
                        <th style="width: 50px; text-align: center">% Prec. Vip</th>
                        <th style="width: 50px; text-align: center">Valor Vip</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class="larger" style="text-align: center; vertical-align: middle">{{ paquete.precio|floatformat:2 }}</td>
                        <td class="larger" style="text-align: center; vertical-align: middle" id="precio_cliente_normal">{{ paquete.precio_cliente_normal|floatformat:2 }}</td>
                        <td style="text-align: center">
                            <input type="text" style="margin-top: 0.5em; width: 70px" id="porciento_cliente_normal" value="{{ paquete.porciento_cliente_normal|floatformat:2 }}" class="imp-50 atright"/>
                        </td>
                        <td class="larger" style="text-align: center; vertical-align: middle" id="valor_cliente_normal">{{ paquete.valor_cliente_normal|floatformat:2 }}</td>
                        <td class="larger" style="text-align: center; vertical-align: middle" id="precio_cliente_corporativo">{{ paquete.precio_cliente_corporativo|floatformat:2 }}</td>
                        <td style="text-align: center">
                            <input type="text" style="margin-top: 0.5em; width: 70px" id="porciento_cliente_corporativo" value="{{ paquete.porciento_cliente_corporativo|floatformat:2 }}" class="imp-50 atright"/>
                        </td>
                        <td class="larger" style="text-align: center; vertical-align: middle" id="valor_cliente_corporativo">{{ paquete.valor_cliente_corporativo|floatformat:2 }}</td>
                        <td class="larger" style="text-align: center; vertical-align: middle" id="precio_cliente_vip">{{ paquete.precio_cliente_vip|floatformat:2 }}</td>
                        <td style="text-align: center">
                            <input type="text" style="margin-top: 0.5em; width: 70px" id="porciento_cliente_vip" value="{{ paquete.porciento_cliente_vip|floatformat:2 }}" class="imp-50 atright"/>
                        </td>
                        <td class="larger" style="text-align: center; vertical-align: middle" id="valor_cliente_vip">{{ paquete.valor_cliente_vip|floatformat:2 }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="span1"></div>
        </div>
    {% endif %}

{% endblock %}