spa/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from inv import (views, ventas, compras, pagos, caja, productos, servicios, paquetes, sesiones, ordenes, clientes,
                 panelclientes, panelcolaborador, proveedores, cajeros, consultas, estadisticas)

from spa.settings import STATIC_URL, STATIC_ROOT, MEDIA_URL, MEDIA_ROOT

urlpatterns = [

    # Admin
    url(r'^admin/', include(admin.site.urls)),

    # Home
    url(r'^$', views.index, name='index'),

    # Login
    url(r'^login$', views.login_user, name='login_user'),

    # Logout
    url(r'^logout$', views.logout_user, name='logout_user'),

    # Change passw
    url(r'^pass$', views.passwd, name='change_password'),

    # Get Data API
    url(r'^get_data$', views.get_data, name='get_data'),

    # Subir Video
    url(r'^subir_video$', views.subir_video, name='subir_video'),

    # VENTAS
    url(r'^ventas$', ventas.view, name='ventas'),

    # COMPRAS
    url(r'^compras$', compras.view, name='compras'),

    # PAGOS
    url(r'^pagos$', pagos.view, name='pagos'),

    # SESION DE CAJA
    url(r'^caja', caja.view, name='caja'),

    # GESTION DE PRODUCTOS
    url(r'^productos$', productos.view, name='productos'),

    # SERVICIOS
    url(r'^servicios$', servicios.view, name='servicios'),

    # PAQUETES
    url(r'^paquetes$', paquetes.view, name='paquetes'),

    # SESIONES
    url(r'^sesiones$', sesiones.view, name='sesiones'),

    # ORDENES DE SERVICIOS
    url(r'^ordenes$', ordenes.view, name='ordenes'),

    # CLIENTES
    url(r'^clientes$', clientes.view, name='clientes'),

    # PANEL CLIENTES
    url(r'^panelclientes$', panelclientes.view, name='panelclientes'),

    # PANEL COLABORADORES
    url(r'^panelcolaborador$', panelcolaborador.view, name='panelcolaborador'),

    # PROVEEDORES
    url(r'^proveedores$', proveedores.view, name='proveedores'),

    # CAJEROS
    url(r'^cajeros$', cajeros.view, name='cajeros'),

    # CONSULTAS
    url(r'^consultas$', consultas.view, name='consultas'),

    # ESTADISTICAS Y GRAFICOS
    url(r'^estadisticas$', estadisticas.view, name='estadisticas'),

]

# Static
urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)

# Media
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

inv/forms.py
import os

from django import forms
from django.forms import DateTimeInput

from inv.models import (UnidadMedida, TipoProducto, TipoDocumento, Banco, TipoTarjetaBanco, ProcesadorPagoTarjeta,
                        FormaDePago, Area, TipoCabello, TipoPiel, TipoServicio, Producto, Servicio, Proveedor,
                        TIPOS_PAQUETES, Factura, Paquete, Cliente, Colaborador)
from spa.settings import (TIPO_CLIENTE_CORPORATIVO, TIPO_PRODUCTO_PARA_VENTA, TIPO_PRODUCTO_PARA_CONSUMO,
                          TIPO_PRODUCTO_RECIBIDO_CONSIGNACION, VALORACION_EXCELENTE, VALORACION_MUYBIEN, 
                          VALORACION_BIEN, VALORACION_REGULAR, VALORACION_MAL, PAQUETE_PROMOCIONAL, PAQUETE_SERVICIO, 
                          TIPO_CLIENTE_NORMAL, TIPO_CLIENTE_VIP)


def deshabilitar_campo(form, campo):
    form.fields[campo].widget.attrs['readonly'] = True
    form.fields[campo].widget.attrs['disabled'] = True


class ExtFileField(forms.FileField):
    """
    * max_upload_size - a number indicating the maximum file size allowed for upload.
            500Kb - 524288
            1MB - 1048576
            2.5MB - 2621440
            5MB - 5242880
            10MB - 10485760
            20MB - 20971520
            50MB - 5242880
            100MB 104857600
            250MB - 214958080
            500MB - 429916160
    t = ExtFileField(ext_whitelist=(".pdf", ".txt"), max_upload_size=)
    """

    def __init__(self, *args, **kwargs):
        ext_whitelist = kwargs.pop("ext_whitelist")
        self.ext_whitelist = [i.lower() for i in ext_whitelist]
        self.max_upload_size = kwargs.pop("max_upload_size")
        super(ExtFileField, self).__init__(*args, **kwargs)

    def clean(self, *args, **kwargs):
        upload = super(ExtFileField, self).clean(*args, **kwargs)
        if upload:
            size = upload.size
            filename = upload.name
            ext = os.path.splitext(filename)[1]
            ext = ext.lower()

            if size == 0 or ext not in self.ext_whitelist or size > self.max_upload_size:
                raise forms.ValidationError("Tipo de fichero o tamanno no permitido!")


class ProductoForm(forms.Form):
    TIPOS_DESTINOS_PRODUCTO = (
        (TIPO_PRODUCTO_PARA_VENTA, 'VENTA'),
        (TIPO_PRODUCTO_PARA_CONSUMO, 'CONSUMO'),
        (TIPO_PRODUCTO_RECIBIDO_CONSIGNACION, 'RECIBIDO CONSIGNACIÓN')
    )
    tipo = forms.ChoiceField(choices=TIPOS_DESTINOS_PRODUCTO, initial=TIPO_PRODUCTO_PARA_VENTA,
                             widget=forms.Select(attrs={'class': 'imp-50', 'separador': 'Datos Generales'}))
    tipoproducto = forms.ModelChoiceField(TipoProducto.objects, label='Categoría',
                                          widget=forms.Select(attrs={'class': 'imp-50'}))
    codigo = forms.CharField(label='Código', required=False, widget=forms.TextInput(attrs={'class': 'imp-30'}))
    descripcion = forms.CharField(label='Descripción', widget=forms.Textarea({'rows': '2'}))
    unidadmedida = forms.ModelChoiceField(UnidadMedida.objects, label='UM',
                                          widget=forms.Select(attrs={'class': 'imp-30'}))
    alias = forms.CharField(max_length=20, label='Alias', required=False,
                            widget=forms.TextInput(attrs={'class': 'imp-30'}))
    codigobarra = forms.CharField(max_length=20, label='Código Barra', required=False,
                                  widget=forms.TextInput(attrs={'class': 'imp-30'}))
    minimo = forms.FloatField(initial='0.00', label='Cantidad Mínima', required=False,
                              widget=forms.TextInput(attrs={'class': 'imp-20 atright'}))
    con_iva = forms.BooleanField(initial=True, required=False, label='Con IVA?')
    precio = forms.FloatField(initial='0.00', label='Referencial', required=False,
                              widget=forms.TextInput(attrs={'class': 'imp-20 atright', 
                                                            'separador': 'Configurar Precios'}))
    precio_cliente_normal = forms.FloatField(initial='0.00', label='Clientes Normales', required=False,
                                             widget=forms.TextInput(attrs={'class': 'imp-20 atright'}))
    precio_cliente_corporativo = forms.FloatField(initial='0.00', label='Clientes Corporativos', required=False,
                                                  widget=forms.TextInput(attrs={'class': 'imp-20 atright'}))
    precio_cliente_vip = forms.FloatField(initial='0.00', label='Clientes Vip', required=False,
                                          widget=forms.TextInput(attrs={'class': 'imp-20 atright'}))

    def for_editproducto(self):
        self.fields['tipo'].widget.attrs['readonly'] = True
        self.fields['codigo'].widget.attrs['readonly'] = True
        self.fields['tipoproducto'].widget.attrs['readonly'] = True


class ServicioForm(forms.Form):
    tiposervicio = forms.ModelChoiceField(TipoServicio.objects, label='Categoría',
                                          widget=forms.Select(attrs={'class': 'imp-50'}))
    codigo = forms.CharField(label='Código', required=False, widget=forms.TextInput(attrs={'class': 'imp-30'}))
    descripcion = forms.CharField(label='Descripción', widget=forms.Textarea({'rows': '2'}))
    unidadmedida = forms.ModelChoiceField(UnidadMedida.objects, label='UM',
                                          widget=forms.Select(attrs={'class': 'imp-30'}))
    alias = forms.CharField(max_length=20, label='Alias', required=False,
                            widget=forms.TextInput(attrs={'class': 'imp-30'}))
    con_iva = forms.BooleanField(initial=True, required=False, label='Con IVA?')
    costo_estandar = forms.FloatField(initial='0.00', label='Costo estándar', required=False,
                                      widget=forms.TextInput(attrs={'class': 'imp-20 atright'}))
    precio = forms.FloatField(initial='0.00', label='Referencial', required=False,
                              widget=forms.TextInput(attrs={'class': 'imp-20 atright', 
                                                            'separador': 'Configurar Precios'}))
    precio_cliente_normal = forms.FloatField(initial='0.00', label='Clientes Normales', required=False,
                                             widget=forms.TextInput(attrs={'class': 'imp-20 atright'}))
    precio_cliente_corporativo = forms.FloatField(initial='0.00', label='Clientes Corporativos', required=False,
                                                  widget=forms.TextInput(attrs={'class': 'imp-20 atright'}))
    precio_cliente_vip = forms.FloatField(initial='0.00', label='Clientes Vip', required=False,
                                          widget=forms.TextInput(attrs={'class': 'imp-20 atright'}))

    def for_edit(self):
        self.fields['codigo'].widget.attrs['readonly'] = True
        self.fields['tiposervicio'].widget.attrs['readonly'] = True


class RecetaForm(forms.Form):
    producto = forms.ModelChoiceField(Producto.objects, label='Producto')

    def for_receta(self, servicio):
        self.fields['producto'].queryset = Producto.objects.filter(tipo=TIPO_PRODUCTO_PARA_CONSUMO).exclude(receta__servicio=servicio)


class PaqueteProductoForm(forms.Form):
    producto = forms.ModelChoiceField(Producto.objects, label='Producto',
                                      widget=forms.Select(attrs={'class': 'myselect2'}))

    def for_paquete(self, paquete):
        self.fields['producto'].queryset = Producto.objects.filter(tipo=TIPO_PRODUCTO_PARA_VENTA).exclude(paqueteproducto__paquete=paquete)


class PaqueteServicioForm(forms.Form):
    servicio = forms.ModelChoiceField(Servicio.objects, label='Servicio',
                                      widget=forms.Select(attrs={'class': 'myselect2'}))

    def for_paquete(self, paquete):
        self.fields['servicio'].queryset = Servicio.objects.all().exclude(paqueteservicio__paquete=paquete)


class ServicioFuturoForm(forms.Form):
    servicio = forms.ModelChoiceField(Servicio.objects, label='Servicio Futuro',
                                      widget=forms.Select(attrs={'class': 'myselect2'}))
    fecha = forms.DateField(label=u"Fecha", input_formats=['%d-%m-%Y'],
                            widget=DateTimeInput(format='%d-%m-%Y', attrs={'class': 'selectorfecha'}))

    def for_serviciofuturo(self, orden):
        self.fields['servicio'].queryset = Servicio.objects.all().exclude(serviciofuturo__orden=orden)


class PaqueteForm(forms.Form):
    codigo = forms.CharField(label='Código', required=False,
                             widget=forms.TextInput(attrs={'class': 'imp-30'}))
    descripcion = forms.CharField(label='Descripción', widget=forms.TextInput())
    alias = forms.CharField(max_length=20, label='Alias', required=False,
                            widget=forms.TextInput(attrs={'class': 'imp-30'}))
    tipo = forms.ChoiceField(choices=TIPOS_PAQUETES, initial=PAQUETE_PROMOCIONAL,
                             widget=forms.Select(attrs={'class': 'imp-30'}))
    sesiones = forms.IntegerField(initial=2, label='Sesiones',
                                  widget=forms.TextInput(attrs={'class': 'imp-10 atright'}))


class ProveedorForm(forms.Form):
    nombre = forms.CharField(max_length=200, label='Razón Social')
    identificacion = forms.CharField(max_length=200, label='Identificación', required=False)
    alias = forms.CharField(max_length=100, label='Alias', required=False)
    pais = forms.CharField(max_length=200, label='Pais', required=False)
    direccion = forms.CharField(max_length=200, label='Dirección', required=False)
    telefono = forms.CharField(max_length=100, label='Teléfono', required=False)
    celular = forms.CharField(max_length=100, label='Celular', required=False)
    email = forms.CharField(max_length=200, label='Email', required=False)
    fax = forms.CharField(max_length=100, label='Fax', required=False)
    logo = ExtFileField(label='Seleccione Logo', required=False,

templates/clientes/add.html
{% extends "ajaxformbs.html" %}
{% block extraheading %}
    <style>
        #formulary table td input#id_email { text-transform: none; }
    </style>
    <script>
        $(function(){
            $("#id_identificacion, #id_nombre, #id_usuario").addClass("validate[required]");

            $("#id_fecha_nacimiento").datepicker({format:"dd-mm-yyyy"}).on('changeDate', function(ev){ $(this).datepicker('hide'); });

            //Activar pestana
            $("#pestana4").addClass('current');

            actualizar_form = function(){
                var tipo = $("#id_tipo").val();
                // cliente corporativo
                if (tipo == 2){
                    $(".corporativo").show();
                    $(".especifico").show();
                    $(".foto").show();
                    $("#id_ruc, #id_razon_social, #id_representante_legal").parent().parent().show();
                    $("#id_tipo_cabello, #id_tipo_piel, #id_caracteristicas_fisicas, #id_alergias, #id_oportunidades_servicios").parent().parent().show();
                    $("#id_foto").parent().parent().show();
                }
                // cliente vip
                else if (tipo == 3){
                    $(".corporativo").hide();
                    $(".especifico").show();
                    $(".foto").show();
                    $("#id_ruc, #id_razon_social, #id_representante_legal").parent().parent().hide();
                    $("#id_tipo_cabello, #id_tipo_piel, #id_caracteristicas_fisicas, #id_alergias, #id_oportunidades_servicios").parent().parent().show();
                    $("#id_foto").parent().parent().show();
                }

                // cliente normal
                else{
                    $(".corporativo").hide();
                    $(".especifico").hide();
                    $(".foto").hide();
                    $("#id_ruc, #id_razon_social, #id_representante_legal").parent().parent().hide();
                    $("#id_tipo_cabello, #id_tipo_piel, #id_caracteristicas_fisicas, #id_alergias, #id_oportunidades_servicios").parent().parent().hide();
                    $("#id_foto").parent().parent().hide();
                }

                return false;
            };

            $("#id_tipo").change(actualizar_form);
            actualizar_form();
        });

    </script>
{% endblock %}

{% block titulo %}{{ title }}{% endblock %}
{% block formaction %}/clientes{% endblock %}
{% block formdestination %}/clientes{% endblock %}
{% block formextra %}
    <input type='hidden' name='action' value='add'/>
{% endblock %}
{% block formback %}/clientes{% endblock %}

templates/clientes/clientes.html
{% extends "basebs.html" %}
{% block heading %}
    <script>
        $(function() {

            $("#search").click(function() {
                var term = $("#searchfield").val().toUpperCase();
                location.href = "/clientes?s="+term;
            });

            $('#searchfield').keyup(function(e) {
                if(e.keyCode == 13) {
                    $("#search").trigger("click");
                }
            });

            $("#tiposel").change(function() {
                var id = $(this).val();
                location.href = '/clientes?t='+id;
            });

            //Activar pestana
            $("#pestana4").addClass('current');

        });

    </script>
{% endblock %}
{% block canvas %}
    <div class='row-fluid'>

        <div class="panel panel-turquesa">
            <div class="panel-heading">
                <div class="row-fluid">
                    <div class="span6">
                        <form class="form-search">
                            <input class='searchinput input-xlarge search-query' type='text' id='searchfield' value='{{ search }}'/>
                            <a href="#" id='search' class='btn btn-success tl' title="Buscar"><i class="fa fa-search"></i> </a>
                            {% if search %}
                                <a href="/clientes" id='allresults' class='btn btn-info tr' title="Ver todos"><i class="fa fa-list"></i></a>
                            {% endif %}
                        </form>
                    </div>
                    <div class="span6">
                        <label for="tiposel"></label>
                        <select id='tiposel' style="float: right;">
                            <option value='0'>-----</option>
                            <option value="1" {% ifequal tipoid 1 %}selected="selected"{% endifequal %}>NORMAL</option>
                            <option value="2" {% ifequal tipoid 2 %}selected="selected"{% endifequal %}>CORPORATIVO</option>
                            <option value="3" {% ifequal tipoid 3 %}selected="selected"{% endifequal %}>VIP</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="panel-body">
                <table class='table table-bordered' cellpadding="0" cellspacing="0">
                    <thead>
                    <tr>
                        <th style="width: 40px; text-align: center">Tipo</th>
                        <th style="width: 90px">Identificaci&oacute;n</th>
                        <th style="width: 250px">Nombre</th>
                        <th>Domicilio</th>
{#                        <th style="width: 90px; text-align: center">FechaNac.</th>#}
                        <th style="width: 200px">Email</th>
                        <th style="width: 80px; text-align: center">Convencional</th>
                        <th style="width: 80px; text-align: center">Celular</th>
                        <th style="width: 100px; text-align: center">Usuario</th>
                        <th style="width: 50px; text-align: center">Foto</th>
                        <th style="width: 80px"></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for cliente in clientes %}
                        <tr>
                            <td style="text-align: center">
                                <label class="badge {% if cliente.tipo == 2 %}badge-success{% elif cliente.tipo == 3 %}badge-info{% else %}{% endif %} tl" title="{% if cliente.tipo == 2 %}Corporativo{% elif cliente.tipo == 3 %}Vip{% else %}Normal{% endif %}">
                                    {{ cliente.get_tipo_display }}
                                </label>
                            </td>
                            <td> {{ cliente.identificacion|default_if_none:"" }} </td>
                            <td> {{ cliente.nombre }} </td>
                            <td> {{ cliente.domicilio|default_if_none:"" }}</td>
{#                            <td style="text-align: center"> {{ cliente.fecha_nacimiento|date:'d-m-Y' }}</td>#}
                            <td> {{ cliente.email }} </td>
                            <td> {{ cliente.telefono|default_if_none:'' }} </td>
                            <td> {{ cliente.celular|default_if_none:'' }} </td>
                            <td> {{ cliente.usuario|default_if_none:'' }} </td>
                            <td style="text-align: center">
                                {% if cliente.foto %}
                                    <a href='{% if cliente.foto %}{{ cliente.download_foto }}{% endif %}' class="{% if cliente.foto %}fancybox{% endif %}" rel="group">
                                        <img src="{{ cliente.download_foto }}" width="25px" height="25px">
                                    </a>
                                {% endif %}
                            </td>
                            <td>
                                <div class="btn-group">
                                    <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#">
                                        <span class="smaller10">Acciones</span>
                                        <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu pull-right list-group">
                                        <li class="smaller10"><a class="list-group-item btn-form" href='/clientes?action=edit&id={{ cliente.id }}'><i class="fa fa-edit fa-fw"></i>&nbsp; Editar el cliente</a></li>
                                        {% if not cliente.en_uso %}
                                            <li class="smaller10"><a class="list-group-item btn-form" href="/clientes?action=delete&id={{ cliente.id }}"><i class="fa fa-times fa-fw"></i>&nbsp; Eliminar el cliente</a></li>
                                        {% endif %}
                                        <li class="smaller10"><a class="list-group-item btn-form" href="/clientes?action=resetear&id={{ cliente.id }}"><i class="fa fa-key"></i> &nbsp;&nbsp;Resetear la Clave</a> </li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="15">
                                {% if tipoid %}
                                    {% if tipoid == 1 %}
                                        No existen clientes <strong>NORMALES</strong> registrados en el sistema
                                    {% elif tipoid == 2 %}
                                        No existen clientes <strong>CORPORATIVOS</strong> registrados en el sistema
                                    {% else %}
                                        No existen clientes <strong>VIP</strong> registrados en el sistema
                                    {% endif %}
                                {% endif %}
                                {% if search %}
                                    No se han encontrado clientes segun la busqueda ingresada
                                {% else %}
                                    No existen clientes registrados en el sistema
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

        </div>

    </div>
    <div class='row-fluid'>
        <div class="span4">
            <a href="/clientes?action=add" class='btn btn-turquesa btn-form'><i class="fa fa-plus"></i> Adicionar</a>
        </div>
        <div class="span8">
            {% if paging.num_pages > 20 %}
                <div class='pagination'>
                    <ul>
                        {% if paging.primera_pagina %}
                            <li><a href="/clientes?page=1">1</a></li>
                            <li><a href="/clientes?page={{ paging.ellipsis_izquierda }}" class="active">...</a></li>
                        {% endif %}
                        {% for pagenumber in paging.paginas %}
                            <li {% ifequal pagenumber page.number %}class='active'{% endifequal %}><a href="/clientes?page={{ pagenumber }}{% if tipoid %}&t={{ tipoid }}{% endif%}">{{ pagenumber }}</a></li>
                        {% endfor %}
                        {% if paging.ultima_pagina %}
                            <li><a href="/clientes?page={{ paging.ellipsis_derecha }}" class="active">...</a></li>
                            <li><a href="/clientes?page={{ paging.num_pages }}">{{ paging.num_pages }}</a></li>
                        {% endif %}
                    </ul>
                </div>
            {% else %}
                <div class='pagination'>
                    <ul>
                        {% for pagenumber in paging.page_range %}
                            <li {% ifequal pagenumber page.number %}class='active'{% endifequal %}><a href="/clientes?{% if search %}s={{ search }}&{% endif %}page={{ pagenumber }}{% if tipoid %}&t={{ tipoid }}{% endif %}">{{ pagenumber }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>
    </div>

{% endblock %}

templates/clientes/delete.html
{% extends "ajaxdeletebs.html" %}
{% block extraheading %}
    <script>
    $(function () {
        //Activar pestana
        $("#pestana4").addClass('current');
    });
    </script>
{% endblock %}
{% block titulo %}{{ title }}{% endblock %}
{% block formback %}/clientes{% endblock %}
{% block formdestination %}/clientes{% endblock %}
{% block formaction %}/clientes{% endblock %}
{% block formactionvalue %}delete{% endblock %}
{% block formobjectid %}{{ cliente.id }}{% endblock %}
{% block formobjectname %}el cliente: <b>{{ cliente }}</b>{% endblock %}

templates/clientes/edit.html
{% extends "ajaxformbs.html" %}
{% block extraheading %}
    <style>
        #formulary table td input#id_email { text-transform: none; }
    </style>
    <script>
        $(function(){
            $("#id_identificacion, #id_nombre, #id_usuario").addClass("validate[required]");

            $("#id_fecha_nacimiento").datepicker({format:"dd-mm-yyyy"}).on('changeDate', function(ev){ $(this).datepicker('hide'); });

            //Activar pestana
            $("#pestana4").addClass('current');

            actualizar_form = function(){
                var tipo = $("#id_tipo").val();
                // cliente corporativo
                if (tipo == 2){
                    $(".corporativo").show();
                    $(".especifico").show();
                    $(".foto").show();
                    $("#id_ruc, #id_razon_social, #id_representante_legal").parent().parent().show();
                    $("#id_tipo_cabello, #id_tipo_piel, #id_caracteristicas_fisicas, #id_alergias, #id_oportunidades_servicios").parent().parent().show();
                    $("#id_foto").parent().parent().show();
                }
                // cliente vip
                else if (tipo == 3){
                    $(".corporativo").hide();
                    $(".especifico").show();
                    $(".foto").show();
                    $("#id_ruc, #id_razon_social, #id_representante_legal").parent().parent().hide();
                    $("#id_tipo_cabello, #id_tipo_piel, #id_caracteristicas_fisicas, #id_alergias, #id_oportunidades_servicios").parent().parent().show();
                    $("#id_foto").parent().parent().show();
                }

                // cliente normal
                else{
                    $(".corporativo").hide();
                    $(".especifico").hide();
                    $(".foto").hide();
                    $("#id_ruc, #id_razon_social, #id_representante_legal").parent().parent().hide();
                    $("#id_tipo_cabello, #id_tipo_piel, #id_caracteristicas_fisicas, #id_alergias, #id_oportunidades_servicios").parent().parent().hide();
                    $("#id_foto").parent().parent().hide();
                }

                return false;
            };

            $("#id_tipo").change(actualizar_form);
            actualizar_form();
        });

    </script>
{% endblock %}
{% block titulo %}{{ title }} {{ cliente }}{% endblock %}
{% block formaction %}/clientes{% endblock %}
{% block formdestination %}/clientes{% endblock %}
{% block formextra %}
    <input type='hidden' name='action' value='edit'/>
    <input type='hidden' name='id' value='{{ cliente.id }}'/>
{% endblock %}
{% block formback %}/clientes{% endblock %}
{% block buttonname %}Guardar{% endblock %}

templates/clientes/resetear.html
{% extends "ajaxconfirmacionbs.html" %}
{% block atras %}/clientes{% endblock %}
{% block titulo %}{{ title }}{% endblock %}
{% block formback %}/clientes{% endblock %}
{% block formdestination %}/clientes?id={{ cliente.id }}{% endblock %}
{% block formaction %}/clientes{% endblock %}
{% block formactionvalue %}resetear{% endblock %}
{% block formobjectid %}{{ cliente.id }}{% endblock %}
{% block mensaje %}Est&aacute; seguro que desea resetear la clave de: {% endblock %}
{% block formobjectrepr %}{{ cliente.usuario.username }}{% endblock %}